language: r
dist: trusty
sudo: true
branches:
  only:
    - dev
cache:
  packages: yes
  directories:
    - $HOME/bin
pandoc_version: 2.5
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update --allow-unauthenticated -y
  - sudo apt-get upgrade --allow-unauthenticated -y
  - sudo apt-get install build-essential
  - sudo apt-get install aptitude
  - sudo apt-get install libstdc++6
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
script:
  - ./_build.sh
  - ./_deploy.sh
 